name: AI PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run AI review workflow
        uses: tauri-apps/gh-action-ai-pr-review@v2
        with:
          provider: anthropic
          model: claude-3-5-sonnet-20241022
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          instructions: prompts/global/review_checklist.md
